#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
# @action
#

# check to see if I used a message, then it will behave as a put
#bash shell script check input argument

# set working directory as the scripts location during the execution of script
# cd "$(dirname "$0")"


ACTION=`basename "$0"`

# check operation systems

if [[ "$(uname)" == "Darwin" ]] ; then
  # Do something under Mac OS X platform
  git add "$*" ;

elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
  # Do something under GNU/Linux platform
  git add "$@" ;

elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
  # Do something under Windows NT platform
  git add "$*" ;
  # nothing here
fi

