#!/usr/bin/env bash
PULLCURRENTBRANCH=$(git rev-parse --abbrev-ref HEAD);

echo "git pull origin \"${PULLCURRENTBRANCH}\" --allow-unrelated-histories"
git pull origin "${PULLCURRENTBRANCH}" --allow-unrelated-histories

