#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
# REF: http://nicolasgallagher.com/git-checkout-specific-files-from-another-branch/
# REF: http://stackoverflow.com/questions/307579/how-do-i-copy-a-version-of-a-single-file-from-one-git-branch-to-another


# if value is not set  -- exit silent it
if [[ -z "$1"  ]] ; then
    echo " "
    echo "Needs two arguments  "
    echo " "
    echo "Sample Usage:     *required"
    echo " "
    echo "    $0    branchname_from     filename_with_path_to_get "
    exit 1;
fi


# if everything else --

# check operation systems
(
  if [[ "$(uname)" == "Darwin" ]] ; then
    # Do something under Mac OS X platform
    git checkout "$1" -- "$2";

  elif [[ "$(cut -c1-5 <<< "$(uname -s)")" == "Linux" ]] ; then
    # Do something under GNU/Linux platform
    git checkout "$1" -- "$2";

  elif [[ "$(cut -c1-10 <<< "$(uname -s)")" == "MINGW32_NT" ]] ; then
    # Do something under Windows NT platform
    git checkout "$1" -- "$2";
  fi
)


