#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#

# if value is not set  -- exit silent it
if [[ -z "$1"  ]] ; then
    echo " "
    echo "$0 Cherry commit one file at time "
    echo " "
    echo " Needs two arguments  "
    echo " "
    echo "Sample Usage:     *required"
    echo " "
    echo "    $0    file_name      \"message\" "
    exit 1;
fi


# if everything else --

# check operation systems
(
  if [[ "$(uname)" == "Darwin" ]] ; then
    # Do something under Mac OS X platform
    git add "$1"
    git commit -m "$1 - $2";

  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
    # Do something under GNU/Linux platform
    git add "$1"
    git commit -m "$1 - $2";

  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
    # Do something under Windows NT platform
    git add "$1"
    git commit -m "$1 - $2";
  fi
)


