#!/usr/bin/env bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
currentbranch=$(git rev-parse --abbrev-ref HEAD)
echo -e "Force Reseting Pull to  ${currentbranch} "
echo -e "git fetch --all "
echo -e " "
echo "...downloads the latest from remote without trying to merge or rebase anything..."

said=$(git fetch --all)

echo "...resets the master branch to what you just fetched."
echo "...The --hard option changes all the files in your working tree to match the files in origin/master"
echo "git reset --hard origin/${currentbranch}"
echo " "
said=$(git reset --hard origin/${currentbranch})
echo "${said} \n\n"
said=$(projectparticipation)
echo "${said} \n\n"
