#!/usr/bin/env bash

.dirs() {
    find * -maxdepth 0 -type d   # mac and linux tested
} # end dirs

.pullsubs() {
  # Perform all actions in
  #        LIST1
  #          for each element in
  #                           LIST2
  local _curdir="${1}"
  local ACTIONS="${2}"
  cd "${_curdir}"
  local local_items="$(.dirs)"
  local one_item  action _cwd
  while read -r one_item; do
  {
    [[ -z "${one_item}" ]] && continue  # if zempty skip
    _cwd="${_curdir}/${one_item}"
    cd "${_cwd}"
    echo "${_cwd}"
    action="${ACTIONS/\{\#\}/$one_item}"  # replace value inside string substitution expresion bash
    eval "${action}"
  }
  done <<< "${local_items}"
  return 0
} # end .pullsubs


CURDIR="${PWD}"
ACTIONS="
if [[ -d .git/ ]] ; then 
{
  pull
}
else
{
  .pullsubs \"$(pwd)/{#}\" \"${ACTIONS}\"
}
fi
"
.pullsubs  "${CURDIR}" "${ACTIONS}"


