#!/usr/bin/env bash

.dirs() {
    find * -maxdepth 0 -type d   # mac and linux tested
}
.pullsubs() {
  # Perform all actions in
  #        LIST1
  #          for each element in
  #                           LIST2
  local _curdir="${1}"
  local ACTIONS="${2}"
  cd "${_curdir}"
  local local_items="$(.dirs)"
  local one_item  action _cwd
  while read -r one_item; do
  {
    if [[ -n "${one_item}" ]] ; then  # if not empty
    {
      _cwd="${_curdir}/${one_item}"
      cd "${_cwd}"
      echo "${_cwd}"
      action="${ACTIONS/\{\#\}/$one_item}"  # replace value inside string substitution expresion bash
      eval "${action}"
    }
    fi
  }
  done <<< "${local_items}"
  return 0
}


CURDIR="${PWD}"
ACTIONS="
if [[ -d .git/ ]] ; then 
{
  pull
}
else
{
  .pullsubs \"$(pwd)/{#}\" \"${ACTIONS}\"
}
fi
"
.pullsubs  "${CURDIR}" "${ACTIONS}"

