#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
.each() {
  local local_actions="${1}"
  local local_items="${2}"
  local one_item
  local one_action
  local action

  while read -r one_item; do
  {
    [ -z "${one_item}" ] && continue  # if z empty skip
    while read -r one_action; do
    {
      [ -z "${one_action}" ] && continue  # if z empty skip
      action="${one_action/\{\#\}/$one_item}"  # replace value inside string substitution expresion bash
      eval ${action}
    }
    done <<< "${local_actions}"
  }
  done <<< "${local_items}"
} # end .each

GET_ALL_SUBDIRS=$(find * -maxdepth 0 -type d | egrep -v "\.git")

CURDIR="${PWD}"
ACTIONS="echo -e \".\"
echo \" \"
echo \"Subdirectory:\"
echo \". \"
echo \". . . . . . .       {#} \"
cd \"${CURDIR}/{#}\"
pwd
[[ -d .git/ ]] && pull
"
cd "${CURDIR}"

# Perform all actions in
#        LIST1
#          for each element in
#                           LIST2
.each  "${ACTIONS}"   "${GET_ALL_SUBDIRS}"

