#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
.each() {
  local local_actions="${1}"
  local local_items="${2}"
  local one_item
  local one_action
  local action

  while read -r one_item; do
  {
    [ -z "${one_item}" ] && continue  # if z empty skip
    while read -r one_action; do
    {
      [ -z "${one_action}" ] && continue  # if z empty skip
      action="${one_action/\{\#\}/$one_item}"  # replace value inside string substitution expresion bash
      eval ${action}
    }
    done <<< "${local_actions}"
  }
  done <<< "${local_items}"
} # end .each

.remove_for_each() {
  local local_actions="${1}"
  local local_items="${2}"
  local one_item
  local one_action
  local action

  while read -r one_item; do
  {
    [ -z "${one_item}" ] && continue  # if z empty skip
    while read -r one_action; do
    {
      [ -z "${one_action}" ] && continue  # if z empty skip
      action="${one_item/$one_action\//}"  # replace value inside string substitution expresion bash
      echo "${action}"
    }
    done <<< "${local_actions}"
  }
  done <<< "${local_items}"
} # end .remove_for_each

echo "Fetch all current new branches"
git fetch 

GET_ALL_REMOTES=$(git remote -v | sed 's/\t/|/g' | cut -d'|'  -f1 | sort | uniq)

ALL_REMOTE_BRANCHES_BRANCHES=$(git branch -r --no-color | sed '1d' | sed 's/[*]//g' | sed 's/\ //g' )
ACTIONS="pwd
git checkout {#}
pull
"

# Remove from the ALL WORDS FROM LIST2 that are match into LIST1
ALL_REMOTE_BRANCHES_BRANCHES_WITHOUT_ORIGIN=$(.remove_for_each "${GET_ALL_REMOTES}" "${ALL_REMOTE_BRANCHES_BRANCHES}")

# Perform all actions in LIST1 for each element in LIST2
.each  "${ACTIONS}" "${ALL_REMOTE_BRANCHES_BRANCHES_WITHOUT_ORIGIN}"

