#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#set -u

function load_colors() {
  [[ -z "${CYAN:-}" ]] && CYAN="\\033[38;5;123m"
  [[ -z "${PURPLE_BLUE:-}" ]] && PURPLE_BLUE="\\033[38;5;93m"
  [[ -z "${YELLOW226:-}" ]] && YELLOW226="\\033[38;5;226m"
  [[ -z "${GRAY241:-}" ]] && GRAY241="\\033[38;5;241m"
  [[ -z "${GRAY242:-}" ]] && GRAY242="\\033[38;5;242m"
  [[ -z "${GRAY243:-}" ]] && GRAY243="\\033[38;5;243m"
  [[ -z "${YELLOW214:-}" ]] && YELLOW214="\\033[38;5;214m"
  [[ -z "${RESET:-}" ]] && RESET="\\033[0m"
  [[ -z "${RED:-}" ]] && RED="\\033[38;5;1m"
  [[ -z "${BRIGHT_BLUE87:-}" ]] && BRIGHT_BLUE87="\\033[38;5;87m"
  GRAYEDOUT="\033[01;30m"
  RED="\033[01;31m"
  GREEN="\033[01;32m"
  YELLOW="\033[01;33m"
  DARKBLUE="\033[01;34m"
  DARKGREEN="\033[38;5;22m"
  PURPLE="\033[01;35m"
  CYAN="\033[01;36m"
  WHITEBOLD="\033[01;37m"

  LIGHTGREEN="\033[38;5;83m"
  LIGHTPINK="\033[1;204m"
  LIGHTYELLOW="\033[38;5;227m"
  GREEN_OVER_DARKBLUE="\033[38;5;76m\033[48;5;17m"
  YELLOW_OVER_DARKBLUE="\033[38;5;220m\033[48;5;20m"
  DARKBLUE_OVER_DARKBLUE="\033[01;34m\033[48;5;20m"

  RESET="\033[0m"
} # end load_colors
load_colors


#PULLCURRENTBRANCH
# ref: http://stackoverflow.com/questions/8190392/is-there-a-git-command-that-returns-the-current-project-name
[[ -z "${PULLCURRENTBRANCH:-}" ]] && PULLCURRENTBRANCH=$(git config --local remote.origin.url|sed -n 's#.*/\([^.]*\)\.git#\1#p');
[[ -z "${GIT_USER_NAME:-}" ]] && GIT_USER_NAME=$(command git config --get user.name 2> /dev/null)
#echo "GIT_USER_NAME=$GIT_USER_NAME"
#KEY?
    if [[ "${PWD}" == *"clis"* ]] ; then
      echo -e "${GRAY242} === ${GRAYEDOUT} "We are in clis" ${GRAY242} === ${RESET}"
      if [[ "${GIT_USER_NAME}" != *"zeusintuivo"* ]] ; then
        sshswitchkey zeus ;
        GIT_USER_NAME=$(command git config --get user.name 2> /dev/null)
      fi
    else
      LOAD_TEMP_KEYS="# Empty script"
      if [ -f .temp_keys ] ; then
        LOAD_TEMP_KEYS=$(<.temp_keys)
        eval "${LOAD_TEMP_KEYS}"
        if [[ -n "${SSH_KEY:-}" ]] && [[ "${GITUSER:-}" != "${GIT_USER_NAME}" ]] ; then
          echo -e "${RED} === ${GRAYEDOUT} required GITUSER:${GRAY241}${GITUSER:-} ${GRAY242}=?= ${GRAY243}${GIT_USER_NAME}${GRAYEDOUT}:GIT_USER_NAME ${RED} === ${RESET}"
          sshswitchkey "${SSH_KEY}"
          GIT_USER_NAME=$(command git config --get user.name 2> /dev/null)
        fi
      fi
    fi

#
# C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --Start
#
test_positives(){
  # REF https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux
  KIND=""
  ls werwerwerwerwerwerwerwerwerwerwerr >/dev/null 2>&1;
  if (( $? == 0 )) ;  then  # Intel processor
    KIND="INTEL"
  fi
  if [ $? == 0 ]; then   # Mac Intel processor
    KIND="${KIND}MAC"
  fi
  echo "${KIND}"
}
PROCESSOR_ERROR=$(test_positives)
# DEBUG MACPOSITIVE MACPOSITIVE echo "${MACPOSITIVE}"
# DEBUG MACPOSITIVE exit 1
#
# C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --End
#


#branchname
PUSH_CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD);

# stop if only one commit from you
test_project_part=$(projectparticipation)
if [[ "${test_project_part}" == *" 1 ${GIT_USER_NAME}"* ]] ; then
{
  echo -e "${BRIGHT_BLUE87} Are you sure? It appears there is a ${RED} 1 commit ${BRIGHT_BLUE87} for${RED}${BRIGHT_BLUE87} ${GIT_USER_NAME}  ${YELLOW226}!!!  ${RESET}"
  echo -e "${BRIGHT_BLUE87}  ${RED} I am stoppping you before you contaminate this with another user.  ${YELLOW226} You can run 'undocommit' though !!!  ${RESET}"
  exit 69;
}
fi


#push
# pull
echo -e "${PURPLE_BLUE} === ${GRAY241} ${GIT_USER_NAME} ${PURPLE_BLUE} pushes to ${CYAN} ${PUSH_CURRENT_BRANCH} ${PURPLE_BLUE} === ${GRAY241} ";

push_result=$(git push origin "${PUSH_CURRENT_BRANCH}"  2>&1 )  # Check and catch capture all stout sdout output, error will return 1 to $?)
err_buff=$?
ERROR_HAPPENED=""
[[ "${PROCESSOR_ERROR}" == *"MAC"* ]] && [ $err_buff != 0 ] && ERROR_HAPPENED="1"
[[ "${PROCESSOR_ERROR}" == *"INTEL"* ]] && (( $err_buff != 0 )) && ERROR_HAPPENED="1"
if [ "${ERROR_HAPPENED}" ]  || \
  [[ "${push_result}" == *"Could not resolve"* ]] || \
  [[ "${push_result}" == *"Repository not found"* ]] || \
  [[ "${push_result}" == *"Could not read from"* ]] || \
  [[ "${push_result}" == *"fatal"* ]] || \
  [[ "${push_result}" == *"FAILED"* ]] || \
  [[ "${push_result}" == *"failed"* ]] || \
  [[ "${push_result}" == *"error"* ]] || \
  [[ "${push_result}" == *"ERROR"* ]] || \
  [[ "${push_result}" == *"denied"* ]] \
  ; then
{
  echo -e "${PURPLE_BLUE} push ${RED}Failed ${YELLOW226}!!!  ${RESET}"
  [[ "${push_result}" == *"Could not resolve"* ]] && echo -e "${BRIGHT_BLUE87} It appears YOU HAVE ${YELLOW226}NO INTERNET CONNECTION \o_0/ ${RESET}"
  [[ "${push_result}" == *"Repository not found"* ]] && echo -e "${BRIGHT_BLUE87} It appears YOU HAVE ${YELLOW226}NO ACCESS TO THIS FOR YOU ${RED} ${GIT_USER_NAME} ${RESET}"
  [[ "${push_result}" == *"Could not read from"* ]] && echo -e "${BRIGHT_BLUE87} It appears YOU HAVE ${YELLOW226}IF IT EXISTS YOU ARE NOT ALLOWED ${RED} ${GIT_USER_NAME} ${YELLOW226}!!! ${RESET}"
  echo -e "${RESET}${push_result}  "
  exit 69;
}
fi

#projectparticipation

echo -e "${test_project_part}"
