#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
# set working directory as the scripts location during the execution of script
# cd "$(dirname "$0")"


# if everything else --
function unstaged_commit_git() {
  local EXCEPTION_LIST UNSTAGE_THIS_FILE
  # check operation systems
  (
    if [[ "$(uname)" == "Darwin" ]] || [[ "$(cut -c1-5 <<< "$(uname -s)")" == "Linux" ]] ; then
    {
      # Do something under Mac OS X platform

      # if file exists in this repo
      if [ -f "commit_exception.list" ] ; then
      {
        EXCEPTION_LIST="$(<commit_exception.list)"
      }
      else
      {
        EXCEPTION_LIST=""
      }
      fi
      while read -r UNSTAGE_THIS_FILE; do
      {

        [[ -z "${UNSTAGE_THIS_FILE}" ]] && continue        # skip if not empty
        [[ ! -f "${UNSTAGE_THIS_FILE}" ]] && continue  # skip if file not exists skip ... like it was deleted, moved or renamed
        git reset HEAD -- "${UNSTAGE_THIS_FILE}" > /dev/null 2>&1
        git restore --staged "${UNSTAGE_THIS_FILE}" > /dev/null 2>&1

      }
      done <<< "${EXCEPTION_LIST}"
    }
    elif [[ "$(cut -c1-10 <<< "$(uname -s)")" == "MINGW32_NT" ]] ; then
    {
      # Do something under Windows NT platform
      echo "PENDING WINDOWS IMPLEMENTATION";
      # nothing here
    }
    fi
  )
} # end unstaged_commit_git
